#!/bin/bash

## Selects file manager application, preference in order listed here

run_filemgr='for f in dolphin nautilus; do command -v "$f" > /dev/null 2>&1 && exec "$f"; done'

qvm-run -q "$1" "bash -c '$run_filemgr'" &disown
