#!/bin/bash

# Takes an arbitrary user input command in a popup window, and executes in the VM ($1)

unset PROMPT_COMMAND

# TEMP FILE NEEDED TO RECORD THE COMMAND
	_temp=$(mktemp -t i3_user_cmd.XXX)
	trap "rm $_temp" EXIT HUP TERM INT QUIT

# POPUP TO RECEIVE THE COMMAND FROM THE USER
	xterm -fa true -fs 14 -T "Run_command_in $1" -e bash -c \
	"i3-msg -q floating enable, move position center ; read -p 'Enter Command:~$ ' _cmd ; echo \$_cmd > $_temp ; exit ;"

# RUN THE COMMAND 
	_user_command=$(cat $_temp) 
	qvm-run -q "$1" "bash -c '$_user_command'" &disown
