#!/bin/bash

##  Launches xterm in template, with legible font size for a 4k 15" monitor
##  Automatically checks distro and runs update/upgrade
##  Enter with no keypress shutsdown template, any other key + Enter stays in terminal

which_distro='if [ -n "`grep -i debian /etc/os-release`" ]; then 
	sudo apt update && sudo apt -y upgrade; else 
	sudo dnf update && sudo dnf -y upgrade; fi'

shutdown='read -p "Enter to close, any other key to stay" r ; echo "$r"; if [ -z "$r" ]; then sudo shutdown now; fi'

xterm='xterm -fa true -fs 11 -hold -e bash -c'


qvm-run -q "$1" "xterm -fa true -fs 11 -hold -e bash -c 'cd /home/user; $which_distro; $shutdown; bash;'" &disown
