#!/bin/sh

## User selects window, screenshot saved in home folder of VM

wininfo=$(xwininfo)
winID=$(echo "$wininfo" | grep "Window id" | sed 's/xwininfo: Window id: //' | sed 's/ .*//')
winNAME=$(echo "$wininfo" | grep "Window id" | sed 's/\"//g' | egrep -o '(\w+)$')
count=1

save=$(printf "%b" "/home/user/" "${winNAME}" "${count}.png") 


## Check if filename already exists. If so increment number until unique name found.

while [ -e "$save" ]; do

	count=$(( $count + 1 ))
	save=$(printf "%b" "/home/user/" "${winNAME}" "${count}.png") 
done

import -window "$winID" "${save}"
