#!/bin/sh

# Copy this script to the template qubes at /usr/bin/ ; and make it executable

usage() {
	echo "dpi: Changes the dpi (or scaling factor) inside of a VM."
	echo ""
	echo "Usage: dpi [-h|-l] <value>"
	echo "   -h: (h)elp. Show this help message"
	echo "   -l: (l)ist. Show the current DPI settings"
	echo "   If <value> is not specified, user is prompted for input"
	echo ""
	echo "Gnome and KDE use a text-scaling-factor between 0.5 and 3"
	echo "XFCE uses native .Xresources DPI, default of 96, and"
	echo "requires re-launching windows for changes to take effect"
}

get_options() {
	while getopts hl _opts ; do
		case $_opts in
			h) usage ; exit 0 ;;
			l) echo "Current setting is:  $dpi_current" ; exit 0 ;;
		esac
	done
}

current_dpi() {
	_de="$XDG_CURRENT_DESKTOP"
	# Different commands for different DEs to change scaling 
	case $_de in
		*XFCE*|*xfce*)
			dpi_current=$(xrdb -query | grep "Xft.dpi" | sed "s/Xft.dpi:[[:blank:]]*//")    ;;
		*GNOME*|*gnome*)
			dpi_current=$(gsettings get org.gnome.desktop.interface text-scaling-factor)    ;;
		*KDE*|*kde*)
			dpi_current=$(kreadconfig5 --file kdeglobals --group KScreen --key ScaleFactor) ;;
	esac
}

get_dpi() {
	case $_de in
		*XFCE*|*xfce*)
			printf "%b" "\nCurrent xrdb dpi is:  $dpi_current" \
				"\nEnter New DPI (Recommend 96 - 288): "
			read dpi
		;;
		*GNOME*|*gnome*|*KDE*|*kde*)
			printf "%b" "\nCurrent scaling factor is:  $dpi_current" \
				"\nEnter new scaling Factor (0.5 - 3.0): "
			read dpi
		;;
	esac
}

check_dpi() {
	case $_de in
		*XFCE*|*xfce*)
			if [ "$dpi" -lt 48 ] || [ "$dpi" -gt 288 ] ; then
				echo "ERROR: DPI is outside of sane range (48-288) for xfce environment"
			fi	
			;;
		*GNOME*|*gnome*|*KDE*|*kde*)
			if { echo "$dpi < 0.5" | bc | grep -qs 1 ;} || { echo "$dpi > 4" | bc | grep -qs 1 ;} ; then
				echo "ERROR: Scaling factor is outside of sane range (0.5-4)"
			fi
			;;
	esac
}

modify_dpi() {
	case $_de in
		*XFCE*|*xfce*) # We delete all 'Xft.dpi' lines in case there are multiple (shouldnt be).
			touch /home/user/.Xresources
			sed -i "/Xft.dpi/ d" /home/user/.Xresources
			echo "Xft.dpi:  $dpi" >> /home/user/.Xresources
			xrdb -merge /home/user/.Xresources
			;;
		*GNOME*|*gnome*) gsettings set org.gnome.desktop.interface text-scaling-factor $dpi ;;
		*KDE*|*kde*) kwriteconfig5 --file kdeglobals --group KScreen --key ScaleFactor $dpi ;;
	esac
}

dpi="$1"
current_dpi
get_options "@"

# If user didnt pass DPI, they can enter it now
[ -z "$dpi" ] && get_dpi

# Check that the DPI entered is sane
check_dpi

# Modify DPI and exit
modify_dpi
